runtime: Remove invalid keyword argument from draw_networkx_nodes
The gr-perf-monitorx tool currently fails with the following error:

gr-perf-monitorx: lost connection (draw_networkx_nodes() got an
unexpected keyword argument 'arrows').

The tool runs correctly once the incorrect keyword argument is removed.

Signed-off-by: Clayton Smith <argilo@gmail.com>